CREATE TABLE users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT UNIQUE NOT NULL,
public_key_sign TEXT NOT NULL,
public_key_encrypt TEXT NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
