CREATE TABLE files (
id INTEGER PRIMARY KEY AUTOINCREMENT,
owner_id INTEGER NOT NULL,
encrypted_filename TEXT NOT NULL,
file_hash TEXT NOT NULL,
signature TEXT NOT NULL,
file_size INTEGER NOT NULL,
total_chunks INTEGER NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(owner_id) REFERENCES users(id)
);

CREATE TABLE file_access (
id INTEGER PRIMARY KEY AUTOINCREMENT,
file_id INTEGER NOT NULL,
user_id INTEGER NOT NULL,
encrypted_symmetric_key TEXT NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(file_id) REFERENCES files(id) ON DELETE CASCADE,
FOREIGN KEY(user_id) REFERENCES users(id),
UNIQUE(file_id, user_id)
);
